name: Deploy Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 17
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'npm'
      - run: npm i --force
      - run: npm run build

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    - name: Connect and deploy
      run: | 
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash bash/nuxic-api.sh"
    - name: Cleanup
      run: rm -rf ~/.ssh
